/**
 * Curated cessation corpus — the ONLY content the RAG index ingests.
 *
 * GENERATED by scripts/build-corpus.mjs from the Scout→Fetch→Curate subagent
 * team. Do NOT hand-edit chunk text; re-run the pipeline (knowledge/README.md).
 * Every entry carries its source URL + retrieval date (hard rule: no source =
 * not ingested). Built: 2026-06-09 · 23 sources · 224 chunks.
 */
import type { Topic } from './sources.config';

export type CorpusEntry = {
  sourceUrl: string;
  sourceName: string;
  domain: string;
  topic: Topic;
  /** true = contains dosing/clinical specifics: stored for reference, never repeated verbatim by Sage. */
  referenceOnly: boolean;
  retrievalDate: string;
  chunks: string[];
};

export const CORPUS: CorpusEntry[] = [
  {
    "sourceUrl": "https://www.cdc.gov/tobacco/campaign/tips/quit-smoking/tips-for-quitting/index.html",
    "sourceName": "CDC",
    "domain": "cdc.gov",
    "topic": "cravings",
    "referenceOnly": true,
    "retrievalDate": "2026-06-09",
    "chunks": [
      "When you have an urge to smoke while using nicotine replacement therapy, you may be able to adjust your medication to get more relief. People using a lower-dose patch may be able to switch to a higher-dose patch, or combine the patch with a faster-acting product like mini-lozenges or gum. If you are taking varenicline or bupropion and still struggle with urges, talk with your healthcare provider about your options.",
      "Before your quit day, get rid of the things that make it easier to smoke. Remove cigarettes, lighters, matches, and ashtrays from your home, your car, and your workplace. Washing your clothes and cleaning your spaces to get rid of the smell of smoke can also reduce the cues that trigger an urge to light up.",
      "Tell the people around you that you are quitting and let them know how they can support you. Having friends, family, and coworkers aware of your plan makes it easier to ask for encouragement when an urge hits. Social support is an important part of staying smoke-free.",
      "Urges to smoke usually fade quickly, especially if you distract yourself until the feeling passes. When an urge hits, try listening to music, going for a walk, calling a friend, playing a game, or watching a video. It helps to make a list of distractions you enjoy before you quit so you are ready when an urge comes.",
      "Keeping your mouth and hands busy can help when you miss the physical habit of smoking. Substitutes like toothpicks, straws, cinnamon sticks, paper clips, pencils, or a squeeze ball give you something to do in place of holding or puffing on a cigarette. These small replacements address the oral and hand-based parts of the smoking habit.",
      "Urges are often driven by specific thoughts such as 'I deserve a cigarette' or 'Just one won't hurt.' Learning to recognize these thoughts lets you challenge them, because not all of our thoughts are true. Prepare counter-responses ahead of time so you can talk back to the thoughts that push you toward smoking.",
      "Instead of fighting an urge head-on, you can observe it without acting on it. Think of an urge like an ocean wave: it builds, peaks, and then naturally subsides, usually within a few minutes. By riding out the wave and letting the craving pass on its own, you can get through it without smoking.",
      "Free support is available if you need help quitting. You can call the quitline at 1-800-QUIT-NOW (1-800-784-8669) to get coaching and additional guidance from trained specialists. The service can help you build a plan and stay on track."
    ]
  },
  {
    "sourceUrl": "https://www.cdc.gov/tobacco/campaign/tips/quit-smoking/7-common-withdrawal-symptoms/index.html",
    "sourceName": "CDC",
    "domain": "cdc.gov",
    "topic": "withdrawal",
    "referenceOnly": false,
    "retrievalDate": "2026-06-09",
    "chunks": [
      "When you stop smoking, your body and brain have to get used to not having nicotine, which can be uncomfortable. Nicotine withdrawal can't hurt you, though, unless you give in and have a cigarette. Over time, withdrawal symptoms fade as long as you stay smokefree.",
      "Cravings or urges to smoke are one of the most common withdrawal symptoms. Almost everyone who smokes regularly has cravings when they quit; they may be mild or can sometimes feel overwhelming. Quit-smoking medicines, physical activity, avoiding your triggers, and remembering your reasons for quitting can all help you get through an urge.",
      "It is very common to feel irritated, grouchy, or easily upset when you quit smoking. This is a normal part of nicotine withdrawal. Deep breathing and reminding yourself that the discomfort is temporary can help you manage these feelings.",
      "Feeling jumpy or restless during the first days or weeks after quitting is a normal withdrawal symptom. Physical activity can help burn off the restless energy. Cutting back on caffeine can also reduce jumpiness during this period.",
      "You may notice that it is harder to concentrate in the first days after you quit smoking, which is very common. Be patient and cut yourself some slack while your brain adjusts. It can help to limit tasks that demand heavy concentration until the symptom passes.",
      "It's common to have some trouble sleeping when you first quit smoking. Avoiding caffeine in the late afternoon and evening can help, as can keeping a consistent sleep schedule. If you use a nicotine patch, removing it before bed may also improve your sleep.",
      "It's normal for your appetite to increase somewhat when you quit smoking, and some people gain weight. Smart snacking on low-calorie foods, staying physically active, and eating mindfully can help you manage hunger and weight. These strategies let you cope with increased appetite without returning to smoking.",
      "Some people feel mood changes such as anxiety, sadness, or depression for a short time after they quit smoking. Smoking might seem to make you feel better in the short term, but that's only because nicotine stops the discomfort of withdrawal, not because it actually helps anxiety or depression. If you don't feel better in a couple of weeks, or your symptoms feel unmanageable, it's important to contact a healthcare provider. For urgent support, the 988 Suicide & Crisis Lifeline is available."
    ]
  },
  {
    "sourceUrl": "https://www.cdc.gov/tobacco/campaign/tips/quit-smoking/quit-smoking-medications/how-quit-smoking-medicines-work/index.html",
    "sourceName": "CDC",
    "domain": "cdc.gov",
    "topic": "mechanism",
    "referenceOnly": false,
    "retrievalDate": "2026-06-09",
    "chunks": [
      "Nicotine Replacement Therapy (NRT) helps with quitting smoking by replacing some of the nicotine you used to get from cigarettes, so you don't feel as uncomfortable after quitting. Unlike smoking, NRT supplies nicotine without the hundreds of harmful chemicals that cigarette smoke contains. This eases withdrawal while removing exposure to the toxic byproducts of combustion.",
      "There are five FDA-approved forms of nicotine replacement therapy: the nicotine patch, gum, lozenge, nasal spray, and oral inhaler. The patch, gum, and lozenge are the most common quit-smoking medicines, and they can be bought without a prescription. The nasal spray and oral inhaler are additional options that work similarly by delivering nicotine to ease withdrawal.",
      "The nicotine patch is a long-acting form of NRT that delivers a steady level of nicotine over time, while products like the gum and lozenge are short-acting and provide faster, on-demand relief. Combining the two types can be more effective than using one alone. Using the long-acting patch at the same time as a short-acting NRT, like the lozenge or gum, can help decrease withdrawal even more.",
      "Some quit-smoking medicines do not contain nicotine and work on the brain in different ways. Bupropion is one such non-nicotine medication that has many effects on the brain, including helping people quit smoking. It decreases craving and other nicotine withdrawal symptoms, making it easier to stay off cigarettes.",
      "Varenicline is another non-nicotine medication that helps people quit smoking, and it works through two distinct mechanisms in the brain. It mimics some of the effects that nicotine has on parts of your brain, which reduces your urge to smoke and eases some withdrawal symptoms. At the same time, it reduces the enjoyment you get from the nicotine in cigarettes.",
      "Varenicline makes it harder to get a nicotine 'buzz' from smoking. It does this by blocking the brain receptors where nicotine would normally attach, so cigarettes become less rewarding. This dual action of easing withdrawal while blunting the pleasurable effects of smoking is what makes the medication useful for quitting."
    ]
  },
  {
    "sourceUrl": "https://www.cdc.gov/tobacco/e-cigarettes/youth-quitting.html",
    "sourceName": "CDC",
    "domain": "cdc.gov",
    "topic": "teen",
    "referenceOnly": false,
    "retrievalDate": "2026-06-09",
    "chunks": [
      "Many free resources are available to help youth reject or quit vaping and all other tobacco use. These resources are organized by audience, including youth themselves, parents and caregivers, educators, and healthcare providers. They offer information, support tools, and live web-based help tailored to teens who want to stop using e-cigarettes.",
      "Teen.smokefree.gov, a resource from the National Cancer Institute, provides information, tips, tools, and live web-based support for teens who want to quit using tobacco products, including e-cigarettes. A companion program, SmokefreeTXT for Teens, delivers quit support directly through text messaging. Together these give young people both interactive online guidance and on-the-go encouragement.",
      "Teens can call 1-800-QUIT-NOW to be connected to their state quitline. State quitlines offer free, confidential support from trained quit coaches and are available in multiple languages. This phone-based option provides personalized help for young people trying to stop vaping.",
      "This is Quitting, a program from Truth Initiative, is a free mobile text-message program designed specifically for young people who want to quit vaping. NOT for Me, from the American Lung Association, is a mobile-friendly quit program aimed at youth ages 14 to 19. Both programs meet teens where they are by delivering support through their phones.",
      "Parents and caregivers play an important role in helping youth quit vaping. The CDC offers fact sheets and resources to help adults start and guide conversations with their children about the risks of e-cigarettes. The This is Quitting program also includes resources specifically for parents and caregivers who want to support a young person trying to quit.",
      "Educators and school administrators have access to CDC fact sheets, conversation cards, and presentation materials to address youth vaping. The Empower Vape-Free Youth campaign and the Stanford Tobacco Prevention Toolkit, available in English and Spanish, provide classroom-ready educational content. Schools are also encouraged to consider supportive policies, including alternatives to suspension, and can use the FDA Vaping Prevention Resource Center.",
      "Healthcare providers can use CDC fact sheets and conversation cards to talk with young patients about quitting e-cigarettes. The American Academy of Pediatrics offers guidance on youth tobacco cessation to support clinicians in counseling adolescents. These materials help providers integrate vaping cessation into routine care for teens.",
      "Additional supporting resources include the E-Cigarette Visual Dictionary, which helps adults recognize vaping devices, and the SAMHSA treatment center locator for finding local treatment services. The CDC also provides media campaign resources to raise awareness about youth vaping. These tools complement the direct quit programs by improving recognition, access to treatment, and public awareness."
    ]
  },
  {
    "sourceUrl": "https://smokefree.gov/challenges-when-quitting/withdrawal",
    "sourceName": "Smokefree.gov (NCI)",
    "domain": "smokefree.gov",
    "topic": "withdrawal",
    "referenceOnly": false,
    "retrievalDate": "2026-06-09",
    "chunks": [
      "Nicotine is what makes tobacco addictive, so when you quit smoking your body has to get used to not having nicotine. This lack of nicotine is what causes nicotine withdrawal symptoms. Nicotine withdrawal is challenging for most smokers, but the good news is that the worst withdrawal symptoms usually last less than two weeks, even though that stretch of time can be really tough.",
      "Most people experience cravings for cigarettes after they quit, and these thoughts and feelings can range from mild to intense or even overwhelming. Helpful ways to manage cravings include making a quit plan ahead of time, distracting yourself when an urge hits, and identifying your personal triggers so you can avoid or prepare for them. You can also text CRAVE to 47848 for support, talk to a healthcare provider about quit-smoking medications, and use a tracking app to stay on course.",
      "Quitting can make people feel irritable or grouchy because change is often hard and can leave you feeling out of sorts. This is a normal part of withdrawal, and the key is to stay committed to your decision to quit while the feeling passes. Reminding yourself that the irritability is temporary can make it easier to ride out.",
      "Trouble sleeping is a common withdrawal symptom after quitting. To sleep better, keep a consistent sleep schedule, remove screens from your bedroom, and limit caffeine and alcohol in the hours before bed. If sleep problems persist, ask your healthcare provider whether any medication side effects could be contributing.",
      "Some people notice that it is harder to concentrate or that their brain feels foggy in the days after they quit. This difficulty concentrating is a temporary effect of nicotine withdrawal. Trying a quit-smoking medication is one option that may help ease this symptom while your body adjusts.",
      "Feeling restless or jumpy is another common reaction when you stop smoking. Physical activity such as taking a walk or doing yardwork can help burn off that nervous energy. Temporarily cutting back on caffeine can also reduce restlessness during this period.",
      "After quitting, some people feel sad, anxious, or depressed as their body adjusts to life without nicotine. It helps to spend time on hobbies you enjoy, exercise, and lean on friends and family for support. You can also call 1-800-QUIT-NOW or use LiveHelp counseling (available Monday through Friday, 9am to 9pm ET) for guidance.",
      "If feelings of sadness, anxiety, or depression become severe or you are in crisis, reach out for immediate help rather than facing it alone. The 988 Suicide and Crisis Lifeline is available for crisis support. Getting support quickly is important, because intense mood changes after quitting are manageable with help.",
      "Increased hunger is a frequent part of nicotine withdrawal, and many people find themselves eating more after they quit. Keeping healthy snacks on hand makes it easier to manage this. Crunchy options work especially well because they help with cravings while also keeping your hands and mouth busy.",
      "To better understand your own situation, smokefree.gov offers a quiz on how strong your nicotine addiction is. Knowing the strength of your dependence can help you build a quitting strategy that fits your needs. Pairing that self-knowledge with the right coping tools makes the withdrawal period more manageable."
    ]
  },
  {
    "sourceUrl": "https://smokefree.gov/challenges-when-quitting/cravings-triggers/how-manage-cravings",
    "sourceName": "Smokefree.gov (NCI)",
    "domain": "smokefree.gov",
    "topic": "cravings",
    "referenceOnly": false,
    "retrievalDate": "2026-06-09",
    "chunks": [
      "Cravings to smoke are uncomfortable, but they do not last forever. Most cravings pass within a few minutes whether or not you smoke. Having a ready list of coping strategies makes it easier to get through each craving as it comes.",
      "Reaching out for support can help you ride out a craving. Call or text a friend or family member for emotional encouragement, or sign up for a text-message support program that sends daily tips. Smartphone quit-smoking apps can also help you track your cravings and smoking patterns so you understand when urges hit.",
      "Free counseling support is available when a craving feels overwhelming. You can call the National Cancer Institute's quitline at 1-877-448-7848 (Monday through Friday, 9 a.m. to 9 p.m. ET) or reach a state quitline at 1-800-784-8669. Trained counselors can also help through online chat services such as the National Cancer Institute's LiveHelp.",
      "Reminding yourself why you decided to quit can carry you through a craving. Keep your personal reasons for quitting somewhere you can review them in the moment as motivation. It can also help to add up the money you save by not buying cigarettes, which makes the benefits of quitting concrete.",
      "Staying busy is one of the most effective ways to distract yourself from a craving. Keep your mouth occupied with sugar-free gum, hard candy, or a glass of water, and switch to a different activity the instant an urge starts. Getting moving with a short walk, a jog, or a few flights of stairs can also push the craving aside.",
      "Slow, deep breathing can calm your body during a craving. Inhale through your nose and exhale through your mouth, repeating this about 10 times or until you feel more relaxed. This simple breathing exercise can be done anywhere and helps the urge pass.",
      "Going to a place where smoking is not allowed removes the option to smoke and gives a craving time to fade. Spend time in smokefree public spaces such as a movie theater, a shop, or a library when an urge strikes. You can also reuse the coping tricks you have relied on before in those smokefree settings.",
      "When a craving is especially strong, combining two forms of nicotine replacement therapy can help. A short-acting product such as a lozenge or gum can be used alongside a long-acting product such as the patch to manage tough cravings. Talk with a healthcare provider or pharmacist about whether combining NRT products is right for you.",
      "Doing something kind for someone else can shift your focus away from a craving. Helping another person redirects your attention and can ease the stress that often triggers the urge to smoke. The good feeling that comes from a good deed gives you something positive to replace the craving.",
      "Whatever strategy you choose, the goal in the moment is simply to get past the urge without smoking. Do whatever it takes to beat the urge, and remind yourself not to smoke even one puff. Each craving you get through without smoking makes the next one easier to handle."
    ]
  },
  {
    "sourceUrl": "https://smokefree.gov/quit-smoking/getting-started/prepare-to-quit",
    "sourceName": "Smokefree.gov (NCI)",
    "domain": "smokefree.gov",
    "topic": "behavioral",
    "referenceOnly": false,
    "retrievalDate": "2026-06-09",
    "chunks": [
      "Set a quit date within one to two weeks of deciding to quit. Giving yourself time to prepare helps you build the confidence and skills you need to stay smokefree, but avoid choosing a date too far in the future because a distant date can weaken your motivation. If you are struggling to commit to a date, a Practice Quit program lets you rehearse quitting for 1, 3, or 5 days before the real attempt.",
      "Create a personalized quit plan to help you stay focused and motivated. A written plan is worth making even if you have already begun quitting, because it organizes your reasons, strategies, and support into one place you can return to.",
      "Before you quit, identify the personal reasons driving your decision. Reflect on what you dislike about smoking, what it costs you, how it affects your health, what continuing would mean for you and your family, and how your life would improve once you stop. Keeping these motivations clear gives you something concrete to draw on when quitting gets hard.",
      "Learn to recognize your triggers, which are the specific people, places, or activities that prompt the urge to smoke. Once you know your triggers, you can plan around them and prepare responses ahead of time rather than being caught off guard.",
      "Cravings are intense urges to smoke, but they are temporary and pass on their own. Prepare a list of distraction activities in advance so that when a craving hits you have ready ways to ride it out until it fades.",
      "Nicotine withdrawal symptoms typically last from a few days to a few weeks. They can include depression, trouble sleeping, irritability, anxiety, and difficulty concentrating. Knowing these symptoms are normal and time-limited makes them easier to manage when they appear.",
      "Nicotine replacement therapy (NRT) can roughly double your chances of quitting smoking for good. It comes in several forms, including gum, patch, nasal spray, inhaler, and lozenge, and many of these are available without a prescription.",
      "Some people should talk with a doctor before using nicotine replacement therapy, including teens, people who are pregnant, and those with serious medical conditions. Checking with a clinician first ensures NRT is appropriate and safe for your situation.",
      "Several free support resources can help you quit. The SmokefreeTXT program is available by texting QUIT to 47848, and the quitSTART smartphone app helps you track cravings and progress. You can also reach the National Cancer Institute Quitline at 1-877-448-7848 or state quitlines at 1-800-784-8669, and use LiveHelp online counseling, with Spanish-language support available.",
      "Tell your family and friends your quit date and your reasons for quitting so they can support you. Ask them to check in on your progress, suggest smokefree activities to do together, and never offer you a cigarette even if you ask. Let them know your mood may change during withdrawal and ask them to be patient with you."
    ]
  },
  {
    "sourceUrl": "https://nida.nih.gov/publications/research-reports/tobacco-nicotine-e-cigarettes/nicotine-addictive",
    "sourceName": "NIH / NIDA",
    "domain": "nida.nih.gov",
    "topic": "mechanism",
    "referenceOnly": false,
    "retrievalDate": "2026-06-09",
    "chunks": [
      "Nicotine is addictive because it drives compulsive use despite negative health consequences, which is the hallmark of addiction. This is why quitting is so hard: roughly half of smokers try to quit each year, but only about 6 percent succeed in any given year, and most people need several attempts before they stop for good. Repeated quit attempts are normal and expected, not a sign of failure.",
      "When someone uses nicotine, it produces a brief feeling of pleasure or euphoria, partly through a surge of endorphins in the brain's reward circuits. More importantly, nicotine increases levels of the neurotransmitter dopamine in those same reward circuits. This dopamine signal reinforces the behavior, teaching the brain to seek out nicotine again and again.",
      "A major reason nicotine is so addictive is how fast it acts. When inhaled, nicotine reaches the brain within about 10 seconds, but the effect fades quickly. This rapid rise and fall pushes people to use again soon to keep the effect going and to avoid the discomfort that follows, creating a tight cycle of repeated dosing throughout the day.",
      "Over time, ongoing nicotine exposure changes how the brain works. It alters the brain's sensitivity and affects circuits involved in learning, stress, and self-control. These lasting changes help explain why cravings and the pull to use can persist well beyond the first days of quitting.",
      "Once a person is dependent on nicotine, stopping triggers withdrawal symptoms that can begin within just a few hours. Common symptoms include irritability, craving, depression, anxiety, trouble concentrating and other cognitive and attention deficits, sleep disturbances, and increased appetite. Knowing these are temporary, physical effects of withdrawal, not permanent states, can make them easier to ride out.",
      "Nicotine withdrawal symptoms typically peak within the first few days after quitting and then subside over the following weeks. Some people experience symptoms that last longer, and genetics can influence how intense and how prolonged withdrawal feels from person to person. This means a slower or harder withdrawal for some individuals is biologically real, not a lack of willpower.",
      "Nicotine is not the only addictive ingredient in tobacco. Research suggests other compounds in tobacco smoke increase nicotine's addictive power: substances that inhibit the enzyme monoamine oxidase (MAO) and acetaldehyde, formed when the sugars in tobacco burn, both appear to enhance nicotine's reinforcing effects. This added chemistry is part of why combustible tobacco can be especially hard to quit."
    ]
  },
  {
    "sourceUrl": "https://nida.nih.gov/publications/research-reports/tobacco-nicotine-e-cigarettes/what-are-treatments-tobacco-dependence",
    "sourceName": "NIH / NIDA",
    "domain": "nida.nih.gov",
    "topic": "behavioral",
    "referenceOnly": false,
    "retrievalDate": "2026-06-09",
    "chunks": [
      "Effective treatments for tobacco and nicotine dependence include both behavioral therapies and FDA-approved medications. Research shows that combining behavioral treatment with medication produces better outcomes than using either approach on its own.",
      "Cognitive Behavioral Therapy (CBT) for smoking cessation helps people recognize the situations and triggers that prompt them to smoke. It teaches relapse-prevention skills, such as relaxation techniques, along with effective coping strategies for managing the urge to smoke.",
      "Motivational Interviewing (MI) is a counseling approach used in smoking cessation. Counselors help patients explore and resolve their ambivalence about quitting and work to strengthen their personal motivation to stop smoking.",
      "Mindfulness-based approaches support quitting by teaching people to increase their awareness of, and detachment from, the sensations, thoughts, and cravings that can lead to relapse. Rather than acting on a craving automatically, the person learns to observe it without being driven by it.",
      "Quitlines are toll-free telephone support services for people trying to stop smoking, reachable in the United States at 800-QUIT-NOW. Research indicates that smokers who participate in three or more counseling calls have a greater likelihood of quitting successfully.",
      "Technology-based interventions, including text-messaging and web-based programs, are effective tools for smoking cessation. Studies have found that adults who receive encouragement, advice, and quitting tips through text messages show improved quit rates.",
      "Nicotine Replacement Therapy (NRT) is an FDA-approved treatment available over the counter in forms such as patches, gum, lozenges, and sprays. Researchers estimate that NRT increases quit rates by roughly 50 to 70 percent compared to quitting without it.",
      "Two non-nicotine FDA-approved medications are used for smoking cessation. Bupropion, an antidepressant, is indicated for smoking cessation and is considered about equally effective to nicotine replacement therapy, while varenicline boosts the odds of successfully quitting and in some studies is more effective than a single form of NRT.",
      "Combination therapy can improve cessation outcomes for some people. For example, research has found that a combination of varenicline plus nicotine replacement therapy was more effective than varenicline used alone.",
      "Precision medicine approaches examine genetic variations that affect how people respond to cessation medications. Research has shown that varenicline worked best for normal nicotine metabolizers, whereas the NRT patch was most effective for slow metabolizers.",
      "Repetitive transcranial magnetic stimulation (rTMS) is an emerging, non-medication treatment for tobacco dependence that shows early promise. In one study, 33 percent of participants remained abstinent from cigarettes six months after receiving the treatment."
    ]
  },
  {
    "sourceUrl": "https://nida.nih.gov/publications/drugfacts/vaping-devices-electronic-cigarettes",
    "sourceName": "NIH / NIDA",
    "domain": "nida.nih.gov",
    "topic": "teen",
    "referenceOnly": false,
    "retrievalDate": "2026-06-09",
    "chunks": [
      "Vaping devices, also called electronic cigarettes or e-cigarettes, are battery-operated tools that let users inhale an aerosol typically containing nicotine, flavorings, and other chemicals. Their designs range from shapes that resemble traditional cigarettes to forms disguised as everyday items like pens or USB sticks. Most contain four parts: a cartridge or pod holding e-liquid with varying amounts of nicotine, a heating element (atomizer), a battery, and a mouthpiece. When the user puffs, the battery activates the heater, which vaporizes the liquid for inhalation.",
      "When a person vapes, nicotine is rapidly absorbed from the lungs into the bloodstream. It stimulates the adrenal glands to release epinephrine (adrenaline), which raises blood pressure, breathing rate, and heart rate. Like other addictive substances, nicotine activates the brain's reward circuits and increases dopamine, which reinforces repeated use despite the health risks.",
      "Nicotine in any form is a highly addictive drug, and vaping can lead to nicotine addiction. Research indicates nicotine can prime the brain's reward system, putting vapers at increased risk for addiction to other drugs as well. This combination of strong physical absorption and reward-circuit reinforcement is what makes the habit so difficult to break.",
      "Vaping devices are the most commonly used form of nicotine among youth in the United States, and they are especially popular among teens. Many teens do not realize the cartridges contain nicotine at all. Easy availability, appealing advertisements, a wide variety of flavors, and a perception that vaping is safer than cigarettes all drive youth adoption. The devices are also easy to conceal and do not produce the odor of tobacco smoke.",
      "The teen years are a critical period for brain development that continues into young adulthood, which makes young nicotine users especially vulnerable to long-lasting effects. Because nicotine affects developing reward systems, continued vaping can cause nicotine addiction and make other drugs such as cocaine and methamphetamine more pleasurable to the developing brain. Nicotine also affects brain circuits that control attention and learning, and additional risks include mood disorders and permanent problems with impulse control.",
      "Early evidence suggests vaping may act as an introductory product that leads to cigarette use. Ninth-graders who used e-cigarettes were more likely to later smoke traditional cigarettes, and one study found high school students who had recently used e-cigarettes were about seven times more likely to report smoking cigarettes roughly six months later. A study also found that about one in four high school students used e-cigarettes for 'dripping,' placing e-liquid directly on heated coils, citing thicker vapor, enhanced flavor, and a stronger throat sensation.",
      "Research suggests that vaping devices may be less harmful than combustible cigarettes for people who switch over completely, but they still damage health. E-cigarette use exposes the lungs to chemicals produced from the e-liquid and from the heating and vaporizing process. Studies have found that e-cigarette vapor can contain known carcinogens, toxic chemicals, and potentially toxic metal nanoparticles. Some cig-a-like brands contain high levels of nickel and chromium from their heating coils, and some contain cadmium, a toxic metal also found in cigarette smoke that causes breathing problems and disease.",
      "The FDA has alerted the public to thousands of reports of serious lung illnesses associated with vaping, including dozens of deaths. Many of the suspect products tested were THC-containing vaping products, though some contained nicotine mixtures or nicotine alone. The CDC identified Vitamin E acetate as a chemical of concern in these lung injuries and recommends avoiding products that contain it, THC-containing vaping products (especially from informal sources), and any modified or street-purchased products.",
      "E-cigarettes are not FDA-approved as a quit-smoking aid, and there is no conclusive scientific evidence that vaping is effective for long-term smoking cessation. In a study of more than 800 people who vaped to quit smoking, only about nine percent reported they had stopped smoking after one year. European research found that adult smokers who vaped nicotine were less likely to have quit and tended to smoke more cigarettes overall. Seven FDA-approved quit aids exist that are proven safe and effective when used as directed.",
      "Government regulation of e-cigarettes has tightened over time. In 2016 the FDA established regulations treating e-cigarettes and their liquids as tobacco products, and under FDA rules minors cannot purchase e-cigarettes in stores or online. In December 2019 the minimum legal sales age was raised from 18 to 21 years, and in January 2020 the FDA issued policy on the sale of flavored cartridges."
    ]
  },
  {
    "sourceUrl": "https://www.cancer.gov/about-cancer/causes-prevention/risk/tobacco/withdrawal-fact-sheet",
    "sourceName": "NCI cancer.gov",
    "domain": "cancer.gov",
    "topic": "withdrawal",
    "referenceOnly": true,
    "retrievalDate": "2026-06-09",
    "chunks": [
      "Because the nicotine in tobacco is highly addictive, people who quit may experience nicotine withdrawal symptoms, especially if they smoked or used other tobacco products heavily for many years. Common symptoms include nicotine cravings, anger, frustration, irritability, difficulty concentrating, insomnia, restlessness, anxiety, depression, and hunger or increased appetite. Less common symptoms include headaches, fatigue, dizziness, coughing, mouth ulcers, and constipation.",
      "Nicotine withdrawal symptoms do subside over time. They are usually worst during the first week after quitting, peaking during the first 3 days, after which the intensity of symptoms usually drops over the first month. However, everyone is different, and some people have withdrawal symptoms for several months after quitting.",
      "Different withdrawal symptoms follow different timelines. Anger, frustration, and irritability tend to peak within 1 week of quitting and may last 2 to 4 weeks. Anxiety usually builds over the first 3 days after quitting and may last several weeks. Depression usually begins within the first day, continues for a couple of weeks, and goes away within a month.",
      "People who use tobacco get used to having a certain level of nicotine in their body, so after quitting, cravings develop when the body wants nicotine. Cravings can begin within an hour or two after the last use of tobacco and may occur frequently for the next few days or weeks before getting farther apart as time passes. During a craving, mood may change and heart rate and blood pressure may go up.",
      "To cope with cravings, remind yourself that cravings will pass, and avoid situations and activities you used to associate with using tobacco. As a substitute for smoking, try chewing on carrots, pickles, apples, celery, sugarless gum, or hard candy, since keeping the mouth busy may stop the psychological need to smoke. A simple breathing exercise can also help: take a deep breath through the nose and blow out slowly through the mouth, repeating 10 times.",
      "To manage anger, frustration, irritability, and anxiety during withdrawal, remind yourself that these feelings are temporary and engage in an enjoyable physical activity such as taking a walk. Reduce caffeine by limiting or avoiding coffee, soda, and tea. Try relaxation techniques such as meditation, getting a massage, soaking in a hot bath, or setting aside quiet time alone every morning and evening.",
      "It is common to feel sad for a period of time soon after quitting smoking or using other tobacco products. People with a history of depression often have more severe withdrawal symptoms, and some studies have found that many people with a history of major depression will have a new major depressive episode after quitting. Helpful strategies include getting together with a friend, identifying specific feelings such as tiredness, loneliness, boredom, or hunger and addressing those needs, doing enjoyable physical activities, and asking a doctor about prescription medications that may help with depression.",
      "People who quit may gain weight due to increased appetite, though the weight gain is usually less than 10 pounds, and the health benefits of quitting far outweigh the risks of a small amount of extra weight. To manage this, balance physical activity with calorie intake and consider consulting a nutritionist or diet counselor. Bupropion and certain nicotine replacement products such as nicotine gum and lozenges can help counteract weight gain.",
      "Common triggers for tobacco use fall into three categories. Social triggers include being around others who use tobacco or attending a social gathering. Emotional triggers include feeling stressed, anxious, bored, lonely, sad, frustrated, or upset after an argument, or feeling happy, excited, or relieved. Pattern or activity triggers include starting the day, being in a car, drinking coffee or tea, and enjoying a meal or an alcoholic beverage.",
      "Situational strategies can help avoid relapse around known triggers. Around smokers, limit contact, do not hold cigarettes for others, and excuse yourself when others light up. For morning routines, plan a different wake-up routine and keep healthy substitutes where cigarettes used to be. Many people find it helpful to drink less alcohol or avoid it completely, and to remove ashtrays, lighters, and cigarettes from the car while keeping healthy substitutes on hand.",
      "Nicotine replacement therapy comes in five FDA-approved forms that deliver measured doses of nicotine to relieve cravings and withdrawal symptoms, increasing the likelihood of quitting successfully. The patch, gum, and lozenge are available over the counter, while the nasal spray and inhaler require a prescription. Getting nicotine from a replacement product is far less harmful than from cigarettes, and long-term use has not been associated with serious harmful effects, though these products are not recommended for people who are pregnant or trying to become pregnant. Using a long-acting form like the patch alongside a short-acting form like the gum or lozenge can be especially helpful, and effectiveness improves when combined with advice or counseling from a health care provider.",
      "Two non-nicotine prescription medications are approved to help with quitting. Varenicline (Chantix), approved by FDA in 2006, may ease nicotine cravings and block the pleasurable effects of nicotine if a person resumes smoking. Bupropion (Zyban), a prescription antidepressant approved in 1997, can reduce withdrawal symptoms and the urge to smoke, can be used safely with nicotine replacement products, and along with nortriptyline can help people with a past history of depression who try to quit. Both medications have several associated side effects, so a person should discuss with their doctor whether the medicine is right for them.",
      "Some people claim that alternative approaches such as hypnosis, acupuncture, acupressure, laser therapy, or electrostimulation may help reduce nicotine withdrawal symptoms, but in clinical studies these therapies have not been found to help people quit, and there is no evidence they help tobacco users who are trying to quit. The evidence is also inconclusive about whether e-cigarettes help with smoking cessation, and FDA has not approved any e-cigarette as a cessation therapy. People who smoke are advised to use evidence-based quit strategies, including FDA-approved cessation medication and smoking cessation counseling.",
      "Free help is available for quitting tobacco. Smokefree.gov, created by NCI's Tobacco Control Research Branch, offers personalized quit plans and trigger management information. The NCI Smoking Quitline at 1-877-44U-QUIT (1-877-448-7848) provides individualized counseling, printed information, and referrals to other sources."
    ]
  },
  {
    "sourceUrl": "https://www.cancer.gov/about-cancer/causes-prevention/risk/tobacco/quit-smoking-pdq",
    "sourceName": "NCI cancer.gov",
    "domain": "cancer.gov",
    "topic": "nrt",
    "referenceOnly": false,
    "retrievalDate": "2026-06-09",
    "chunks": [
      "Smoking causes at least 11 types of cancer, including lung, throat, mouth, esophageal, stomach, pancreatic, kidney, bladder, and cervical cancers, as well as acute myeloid leukemia. A smoker's risk of cancer is 2 to 10 times higher than that of a person who has never smoked, depending on how long and how much they have smoked. Smoking is also linked to heart disease, stroke, emphysema, bronchitis, cataracts, and bone disease.",
      "Quitting smoking lowers cancer risk over time. People who quit reduce their lung cancer risk by 30% to 50% after 10 years compared with people who keep smoking. The risk of mouth and esophageal cancer drops by about half within 5 years after quitting.",
      "Nicotine is the addictive substance in tobacco, and breaking that addiction is central to quitting. When a person stops using nicotine, they may experience withdrawal symptoms such as feeling depressed or nervous, having trouble thinking clearly, or having trouble sleeping. Cessation medications work in part by reducing these withdrawal symptoms.",
      "Healthcare providers play a key role in helping people quit by asking about smoking at every visit, advising the person to quit, assessing their willingness to do so, and helping them plan. A typical plan includes setting a quit date, providing self-help materials, recommending drug treatment, and scheduling follow-up appointments. This structured provider involvement improves the chances of successfully quitting.",
      "Behavioral counseling improves quit rates, especially when combined with other support. In the Lung Health Study, heavy smokers who received doctor counseling along with group behavioral sessions involving other smokers had better quit rates and a reduced risk of lung cancer, other cancers, heart disease, and respiratory disease. Combining counseling with medication tends to work better than either approach alone.",
      "Peer counseling can be particularly effective for certain groups. Childhood cancer survivors responded better to peer-counseling programs, in which trained survivors support others trying to quit, than to self-help approaches alone. Matching the type of support to the person's situation can improve outcomes.",
      "Nicotine replacement therapy (NRT) supplies controlled amounts of nicotine to ease withdrawal and help break the addiction. NRT products include nicotine gum, patches, nasal spray, inhalers, and lozenges, and they can be used alone or in combination. They help reduce withdrawal symptoms such as depression, nervousness, difficulty concentrating, and sleep problems.",
      "Two non-nicotine prescription medications are used to help people quit smoking: bupropion (sold as Zyban) and varenicline (sold as Chantix). Both reduce nicotine cravings and withdrawal symptoms. They are taken under a healthcare provider's guidance as part of a quit plan.",
      "Cessation medications carry safety considerations that should be discussed with a healthcare provider. Bupropion and varenicline may cause serious psychiatric effects, including changes in behavior, aggression, anxiety, depression, and suicidal thoughts. Varenicline may also cause serious heart problems.",
      "Nicotine replacement therapy is not appropriate for everyone. It is generally not recommended for people who are pregnant or breastfeeding, for teenagers, or for those with heart rhythm problems, uncontrolled high blood pressure, esophagitis, ulcers, insulin-dependent diabetes, or asthma. People in these groups should talk with a healthcare provider before using NRT.",
      "Cutting back on cigarettes is less effective than quitting completely and can carry hidden risks. People who reduce how much they smoke may inhale more deeply or smoke more of each cigarette, which offsets some of the benefit. Nicotine replacement products can help reduce the number of cigarettes smoked, but this effect does not appear to last over time, so full cessation remains the goal.",
      "Free resources are available to support quitting. These include the website www.smokefree.gov, the QuitGuide app, and the booklet Clearing the Air: Quit Smoking Today, which can be requested by calling 1-800-422-6237."
    ]
  },
  {
    "sourceUrl": "https://cancercontrol.cancer.gov/brp/tcrb/smoking-cessation",
    "sourceName": "NCI cancer.gov",
    "domain": "cancer.gov",
    "topic": "behavioral",
    "referenceOnly": false,
    "retrievalDate": "2026-06-09",
    "chunks": [
      "Despite progress in reducing smoking prevalence in the United States, smoking remains a major threat to public health. Reductions in smoking have been uneven across the population, and prevalence continues to remain high among certain sub-populations. Research in this area covers the causes of tobacco use as well as a broad range of behavioral and pharmacological interventions to help people stop smoking.",
      "Free, evidence-based smoking cessation support is available through publicly funded online and mobile resources. These include cessation websites, SMS text-messaging quit programs, smartphone apps, and social media support, offered in both English and Spanish. The goal is to provide on-demand information and support to people trying to quit.",
      "Cessation support programs can be tailored to specific groups who may face distinct challenges when quitting. Specialized programs exist for women, teens, veterans, and adults over 60. Matching support to a person's circumstances is part of an evidence-based approach to cessation.",
      "Integrating tobacco cessation treatment into routine cancer care helps patients who smoke quit. Initiatives have worked to help cancer centers build and sustain tobacco cessation treatment programs and to address cessation routinely with cancer patients. This is done in part by refining electronic medical records and clinical workflows so that cessation treatment is offered consistently.",
      "Smoking cessation can be effectively delivered in the context of lung cancer screening. Research collaborations develop and test approaches that connect people undergoing lung cancer screening with cessation treatment. Pairing screening visits with cessation support reaches smokers at a moment when they are engaged with the health system.",
      "Tobacco use frequently co-occurs with other substance use. Research that integrates resources across alcohol, drug abuse, and cancer programs addresses poly-substance or multi-substance use, abuse, and addiction together. Recognizing these overlapping addictions can inform more comprehensive cessation and treatment strategies."
    ]
  },
  {
    "sourceUrl": "https://www.who.int/news/item/02-07-2024-who-releases-first-ever-clinical-treatment-guideline-for-tobacco-cessation-in-adults",
    "sourceName": "WHO",
    "domain": "who.int",
    "topic": "behavioral",
    "referenceOnly": false,
    "retrievalDate": "2026-06-09",
    "chunks": [
      "In July 2024, the World Health Organization released its first-ever clinical treatment guideline for tobacco cessation in adults. The guideline is aimed at supporting the more than 750 million tobacco users worldwide who want to quit but often lack access to effective help. It addresses cessation across all forms of tobacco use.",
      "The guideline covers strategies for quitting a wide range of tobacco products, including cigarettes, waterpipes, smokeless tobacco, cigars, roll-your-own tobacco, and heated tobacco products. This broad scope reflects that dependence and the need for cessation support extend well beyond conventional cigarettes.",
      "WHO recommends a combination of behavioral support and pharmacological treatment to help people stop using tobacco. Combining counseling with medication is more effective than either approach alone, and the guideline frames these two pillars as complementary parts of cessation care.",
      "For pharmacological support, WHO recommends four medications shown to help people quit: varenicline, nicotine replacement therapy (NRT), bupropion, and cytisine. These medications are intended to be offered alongside behavioral support as part of a comprehensive cessation plan.",
      "Behavioral support can begin with brief advice from a health worker, typically lasting between 30 seconds and 3 minutes, delivered during routine healthcare visits. Even these short interventions, integrated into ordinary clinical encounters, can meaningfully increase a person's likelihood of quitting tobacco.",
      "For people who need more help, the guideline recommends intensive behavioral support delivered through individual counseling, group counseling, or telephone counseling. This more structured support is designed for tobacco users who require ongoing assistance beyond a brief conversation.",
      "WHO also recognizes digital cessation interventions as a useful tool, including text messaging programs, smartphone apps, and internet-based programs. These digital options can extend support to people who may not easily reach in-person services.",
      "A large treatment gap remains: more than 60% of the world's 1.25 billion tobacco users say they want to quit, yet about 70% lack access to effective cessation services because of limited health-system resources. WHO encourages countries to provide cessation treatments at no cost or reduced cost to improve access.",
      "In April 2024, nicotine gum and patch products were granted WHO prequalification, marking the first nicotine replacement therapy products to receive this status. Prequalification is intended to help expand reliable access to quality-assured cessation medicines, particularly in lower-resource settings."
    ]
  },
  {
    "sourceUrl": "https://www.who.int/news-room/fact-sheets/detail/tobacco",
    "sourceName": "WHO",
    "domain": "who.int",
    "topic": "behavioral",
    "referenceOnly": false,
    "retrievalDate": "2026-06-09",
    "chunks": [
      "Tobacco kills up to half of its users who do not quit. Each year tobacco use causes more than 7 million deaths, a toll that includes an estimated 1.6 million non-smokers who die from exposure to second-hand smoke. There is no safe level of exposure, and all forms of tobacco are harmful.",
      "Around 80% of the world's 1.3 billion tobacco users live in low- and middle-income countries, where the burden of tobacco-related illness and death is heaviest. This concentration reflects where the human and economic costs of tobacco fall most severely.",
      "Cigarettes are the most common form of tobacco consumed worldwide, but they are far from the only one. Other products include waterpipes, cigars, heated tobacco products, bidis, kreteks, and smokeless tobacco. Because all of these forms are harmful, switching between them does not make tobacco use safe.",
      "Second-hand smoke is the smoke that fills enclosed spaces when people burn tobacco products. Exposure causes serious cardiovascular and respiratory diseases, including coronary heart disease and lung cancer, and is responsible for around 1.6 million premature deaths every year. Protecting non-smokers from this smoke is a core part of reducing tobacco harm.",
      "Comprehensive smoke-free laws protect people from second-hand smoke in workplaces and public spaces. As of the data reported, more than one-third of the global population across 79 countries is covered by such laws. These protections benefit both smokers and the non-smokers around them.",
      "Counselling and medication can more than double a tobacco user's chance of quitting successfully. Combining behavioral support with treatment is therefore far more effective than trying to quit with neither. This makes access to structured cessation help a key lever for anyone trying to stop.",
      "Despite the proven benefit of cessation support, national comprehensive cessation services with full or partial cost-coverage are available in only 31 countries. This gap means many tobacco users who want to quit lack affordable access to the counselling and treatment that would improve their odds.",
      "WHO adopted the Framework Convention on Tobacco Control (FCTC) in 2003 as the first international public health treaty, and it now has 183 Party countries. The treaty provides the foundation for coordinated global action to reduce tobacco use and protect populations from its harms.",
      "To help countries put the treaty into practice, WHO introduced the MPOWER package of measures in 2007. The six MPOWER measures are: Monitor tobacco use and prevention policies, Protect people from tobacco smoke, Offer help to quit, Warn about the dangers of tobacco, Enforce bans on advertising and promotion, and Raise taxes on tobacco. Together these measures support both prevention and successful quitting."
    ]
  },
  {
    "sourceUrl": "https://www.who.int/news-room/questions-and-answers/item/tobacco-health-benefits-of-smoking-cessation",
    "sourceName": "WHO",
    "domain": "who.int",
    "topic": "mechanism",
    "referenceOnly": false,
    "retrievalDate": "2026-06-09",
    "chunks": [
      "Quitting smoking triggers measurable physiological recovery almost immediately. Within 20 minutes of your last cigarette, your heart rate and blood pressure drop. Within 12 hours, the carbon monoxide level in your blood falls back to normal.",
      "Recovery continues over the following weeks and months. Between 2 and 12 weeks after quitting, your circulation improves and your lung function increases. Within 1 to 9 months, coughing and shortness of breath decrease as the lungs begin to clear.",
      "Cardiovascular risk falls steadily after quitting. One year after stopping, the risk of coronary heart disease is about half that of someone who still smokes. After 5 to 15 years, the risk of stroke is reduced to that of a non-smoker.",
      "Cancer and long-term heart risks decline over a longer horizon. About 10 years after quitting, the risk of lung cancer falls to roughly half that of a smoker, and the risk of cancers of the mouth, throat, esophagus, bladder, cervix, and pancreas also decreases. By 15 years after quitting, the risk of coronary heart disease is the same as that of a non-smoker.",
      "Quitting earlier in life yields the greatest gains in life expectancy. People who quit smoking at around age 30 gain nearly 10 years of life expectancy, those who quit at 40 gain about 9 years, those who quit at 50 gain about 6 years, and those who quit at 60 gain about 3 years. Even quitting later in life produces meaningful benefits.",
      "The benefits of quitting apply even to people who already have a smoking-related illness. For someone who has had a heart attack, stopping smoking cuts the risk of having another one by about half.",
      "Quitting protects the people around the smoker, not just the smoker. When a parent or caregiver stops smoking, children exposed to second-hand smoke face a lower excess risk of disease, especially respiratory conditions such as asthma and ear infections.",
      "Smoking cessation improves reproductive and sexual health. Quitting reduces the risk of impotence and infertility, and for pregnancies it lowers the risk of premature birth, low birth weight, and miscarriage."
    ]
  },
  {
    "sourceUrl": "https://www.ncbi.nlm.nih.gov/books/NBK555596/",
    "sourceName": "PubMed Central",
    "domain": "ncbi.nlm.nih.gov",
    "topic": "nrt",
    "referenceOnly": true,
    "retrievalDate": "2026-06-09",
    "chunks": [
      "Nicotine addiction is a chronic, relapsing condition, and nicotine is highly addictive, comparable to heroin and cocaine. Smoking extends well beyond simple habit; it involves genuine physiological dependence that often requires professional treatment rather than willpower alone. The United States now has more former smokers than current smokers, yet of the roughly two-thirds of adult smokers who want to quit and the half who try each year, fewer than 10 percent stay abstinent for six months or longer.",
      "FDA-approved cessation medications work by reducing nicotine withdrawal symptoms and by reducing or eliminating the reinforcing effects of smoking, in part by desensitizing nicotinic receptors in the brain. Used as directed, these medications roughly double or triple a smoker's chances of quitting compared with placebo. There are seven FDA-approved first-line medications: five forms of nicotine replacement therapy plus two non-nicotine medications.",
      "Nicotine replacement therapy comes in five forms. The transdermal patch delivers nicotine steadily and has the highest adherence of any NRT form. Nicotine gum and lozenge are fast-acting and available over the counter, with the lozenge being particularly useful for heavy smokers. The nicotine nasal spray is prescription-only and provides the most rapid nicotine delivery but has the lowest adherence, while the prescription oral inhaler offers the behavioral satisfaction of a hand-to-mouth action.",
      "Overall, nicotine replacement therapy increases the likelihood of staying abstinent for six months or more, with a relative risk of about 1.60 versus placebo. Combination NRT, such as pairing the steady-release patch with a faster-acting gum, lozenge, spray, or inhaler, produces higher quit rates than using a single form alone. Higher dosages or combination approaches help optimize outcomes for heavier smokers.",
      "Two non-nicotine medications are FDA-approved as first-line cessation treatments. Bupropion is an antidepressant used here for cessation; it is contraindicated in people with seizure disorders or a recent heart attack and has an odds ratio for quit success of about 1.82. Varenicline is a partial agonist at nicotinic receptors and is the single most effective medication, with an odds ratio of about 2.88, though it carries warnings that warrant clinical monitoring. Both medications require a prescription and clinician oversight to set the correct dose and schedule.",
      "As a quit attempt progresses, acute nicotine withdrawal gradually fades, but other challenges persist. Smokers commonly experience intermittent negative emotional states, repeated urges to smoke, reduced motivation, and lower self-efficacy that continue to undermine cessation. Environmental cues and triggers associated with smoking raise the risk of relapse even after the physical withdrawal has eased.",
      "Most smokers need multiple quit attempts before they succeed permanently, sometimes 30 or more, and most relapses happen within the first hours, days, or weeks. Relapse prevention therapy gives smokers concrete coping strategies for high-risk situations. Behavioral interventions alone show mixed results for preventing relapse, but extending pharmacologic treatment, such as a longer varenicline course, shows promise for keeping people quit.",
      "Several behavioral therapies improve cessation outcomes. Cognitive behavioral therapy produces higher abstinence rates than basic advice or health education, especially when combined with NRT. Motivational interviewing, a non-confrontational approach that explores ambivalence, raises quit success with a relative risk of about 1.26 over brief advice, and acceptance and commitment therapy, which teaches people to accept urges and withdrawal sensations while reconnecting with personal values, reached 32 percent quit rates at 12 months versus 18 percent for medication alone in one study.",
      "Counseling intensity matters, showing a clear dose-response relationship in which more contact yields higher quit rates. The 5 A's framework for clinicians is Ask about tobacco use, Advise to quit, Assess willingness, Assist with medication and counseling, and Arrange follow-up. Even brief physician advice under three minutes improves quitting, and individual in-person counseling achieves roughly 16.8 percent abstinence versus 10.8 percent for controls, with intensive weekly sessions over several weeks producing the strongest results.",
      "Telephone quitlines are a proven cessation resource, and proactive multi-call programs outperform reactive services that only answer incoming calls, with multiple proactive sessions yielding a relative risk of about 1.37 for quitting. Adding NRT to quitline counseling increases both uptake and quit rates, yet quitlines reach only about 1 percent of smokers each year, largely because of limited funding. Digital tools also help: interactive websites and text-message programs roughly double short-term abstinence, though their effects often diminish after six months.",
      "Smoking cessation is among the most cost-effective of all preventive health services, and brief physician counseling in particular delivers strong value. Despite this, treatment is badly underused: fewer than one-third of smokers attempting to quit use cessation counseling or FDA-approved medication. Barriers include lack of insurance, weak coverage of cessation treatments, limited clinician training, underfunded quitlines, and the lingering misconception that quitting is purely a matter of willpower rather than something medical treatment can support."
    ]
  },
  {
    "sourceUrl": "https://pmc.ncbi.nlm.nih.gov/articles/PMC4636196/",
    "sourceName": "PubMed Central",
    "domain": "ncbi.nlm.nih.gov",
    "topic": "relapse",
    "referenceOnly": false,
    "retrievalDate": "2026-06-09",
    "chunks": [
      "Most people who try to quit smoking relapse. Without formal treatment, roughly 95 to 98 percent of people who quit return to smoking within 6 to 12 months. This makes preventing relapse, not just achieving initial abstinence, a central goal of any cessation effort.",
      "Quitting produces measurable health benefits almost immediately. Within about 20 minutes of the last cigarette, heart rate and blood pressure begin to drop, and roughly 12 hours after quitting, carbon monoxide levels in the blood return to normal. These early signs of recovery underscore why staying quit, even through difficult early days, matters.",
      "Behavioral therapy is a core, evidence-supported approach to quitting and staying quit. It typically combines motivational support, behavioral contracting, reinforcement for not smoking, relaxation training, and coping-skills practice. Meta-analyses show it works in both group and individual formats.",
      "Relapse prevention is a cognitive-behavioral strategy that teaches people to anticipate and manage the situations most likely to trigger a return to smoking. Clients learn to identify high-risk situations, reframe their expectations, and handle social pressure to smoke. Crucially, they are taught to treat a lapse as a learning opportunity rather than a total failure, which helps a single slip from becoming a full relapse.",
      "Several medication categories are recognized as first-line aids for quitting smoking. These include nicotine replacement therapies such as gum, patch, nasal spray, lozenge, and inhaler, along with bupropion (an antidepressant) and varenicline. Clonidine and nortriptyline are considered second-line options.",
      "Medication on its own is not enough for most people. When used without counseling support, these medications still leave relapse rates above 50 percent. The evidence strongly favors combining pharmacologic aids with behavioral counseling rather than relying on either alone.",
      "Brief advice from a healthcare provider has a real, if modest, effect. A simple 'stop smoking' message from a clinician raises longer-term abstinence rates by about 1 to 3 percent among people who were not otherwise seeking treatment. Because it reaches large numbers of smokers, this small effect adds up at a population level.",
      "Counseling does not have to be delivered face to face to be effective. Internet and computer-based programs can rival in-person brief interventions, and telephone counseling shows a dose-response pattern, with three or more calls outperforming just one or two. Text-message programs appear less effective for sustaining abstinence over the long term.",
      "Motivational enhancement approaches can help, particularly for people not actively seeking to quit. A meta-analysis of 14 randomized trials found modest positive effects compared with brief advice alone, with the strongest benefit among smokers who were not treatment-seeking. This makes motivational techniques a useful entry point for engaging ambivalent smokers.",
      "Quitting strategy and timing have been studied directly. Using nicotine replacement to reduce smoking before quitting roughly doubled the odds of 6-month abstinence compared with placebo, and comparisons of abrupt versus gradual cessation found no significant difference in relapse. For pregnant women, a meta-analysis of 15 studies found that self-help interventions nearly doubled the odds of staying abstinent.",
      "Tailoring support to specific populations improves outcomes. For pregnant and postpartum patients, combining education with relapse prevention, brief advice, and motivational enhancement shows strong effects. For people with cardiovascular disease, psychotherapeutic, telephone, and self-help interventions help significantly, and sustained abstinence reduces the subsequent risk of death by about one-third.",
      "People with psychological disorders benefit from tailored cessation approaches. Cognitive therapy and behavioral activation are effective for managing depressive symptoms that can accompany quitting, and bupropion appears most beneficial for patients with schizophrenia. Matching the intervention to a person's mental health profile improves the odds of staying smoke-free."
    ]
  },
  {
    "sourceUrl": "https://pmc.ncbi.nlm.nih.gov/articles/PMC4542051/",
    "sourceName": "PubMed Central",
    "domain": "ncbi.nlm.nih.gov",
    "topic": "withdrawal",
    "referenceOnly": false,
    "retrievalDate": "2026-06-09",
    "chunks": [
      "Nicotine withdrawal symptoms typically begin 4 to 24 hours after a person stops chronic tobacco use. They tend to peak around the third day and then gradually taper off over the following three to four weeks. Understanding this timeline helps people anticipate that the worst of the discomfort is short-lived and that symptoms steadily ease over the coming weeks.",
      "The DSM-5 recognizes seven primary nicotine withdrawal symptoms: irritability, anger, or frustration; anxiety; depressed mood; difficulty concentrating; increased appetite; insomnia; and restlessness. Additional commonly reported symptoms include constipation, dizziness, nightmares, nausea, and sore throat. These reflect the body and brain readjusting to the absence of nicotine.",
      "Withdrawal symptoms fall into three broad categories. Affective symptoms include anxiety, loss of pleasure (anhedonia), depression, dysphoria, heightened pain sensitivity, and irritability. Somatic symptoms include tremors, slowed heart rate, gastrointestinal discomfort, and increased appetite. Cognitive symptoms include difficulty concentrating and impaired memory.",
      "Genetics play a substantial role in nicotine dependence and withdrawal. Heritability is estimated to account for 50 to 75 percent of the risk for dependence, depending on the population studied. Genetic factors explain roughly 29 to 53 percent of the variance in withdrawal symptoms and about 50 percent of the variance in how successful a person is at quitting. This means that differences in how hard quitting feels are partly biological and not simply a matter of willpower.",
      "How a person metabolizes nicotine, influenced by variants of the CYP2A6 enzyme, affects both withdrawal severity and quitting success. People who carry a null-activity allele that slows nicotine metabolism are about twice as likely to quit smoking, while those with high-activity alleles that clear nicotine faster tend to experience more severe withdrawal. Variation in a nicotinic receptor gene (CHRNA5, SNP rs16969968) is also associated with altered receptor responsiveness and dependence risk.",
      "Chronic nicotine exposure increases the number of nicotine-binding sites in the brain, a process called receptor upregulation. PET imaging studies show that chronic smokers can completely saturate their brain's nicotinic receptors throughout the day. This neuroadaptation is part of why the brain comes to expect a steady supply of nicotine.",
      "Nicotinic receptors also undergo desensitization with chronic nicotine exposure, meaning they become less responsive even though more of them are present. Recovery from desensitization happens on a timescale of seconds to hours. During withdrawal this creates a mismatch: there are many more receptors, but they respond poorly to the brain's natural signaling, which contributes to the discomfort of quitting.",
      "Nicotine withdrawal symptoms can be relieved either by administering nicotine itself, as with nicotine replacement strategies such as patches or gum, or by using pharmacological cessation aids such as bupropion or varenicline. These approaches work by easing the neural disruption that the absence of nicotine produces. A clinician should guide the choice and use of any medication.",
      "During withdrawal, dopamine signaling in the brain's reward circuitry is reduced. In animal models, basal dopamine levels in the nucleus accumbens were observed to remain lowered for at least five days following chronic nicotine exposure. This dip in dopamine helps explain the low mood, irritability, and reduced sense of pleasure that often accompany the early days of quitting.",
      "Specific brain circuits drive different aspects of withdrawal. The medial habenula-interpeduncular nucleus pathway is central to the physical, somatic symptoms of withdrawal. Meanwhile, the extended amygdala, including the bed nucleus of the stria terminalis and the central nucleus of the amygdala, is involved in stress-related withdrawal: withdrawal raises corticotropin-releasing factor in the amygdala, and blocking its receptors reduces withdrawal-related anxiety-like behavior.",
      "Different nicotinic receptor subunits mediate distinct withdrawal symptoms. The alpha-5 subunit is essential for physical, somatic withdrawal signs, while the alpha-6 and beta-2 subunits are tied more to the affective symptoms such as anxiety. This separation suggests that the physical and emotional sides of withdrawal arise from partly different biological systems.",
      "Cognitive symptoms of withdrawal, such as difficulty concentrating and memory problems, are linked to the hippocampus. In animal studies, withdrawal impaired contextual learning, and administering nicotine reversed this deficit. This supports the experience many quitters report of mental fog and trouble focusing in the early phase of cessation."
    ]
  },
  {
    "sourceUrl": "https://www.ncbi.nlm.nih.gov/books/NBK493148/",
    "sourceName": "PubMed Central",
    "domain": "ncbi.nlm.nih.gov",
    "topic": "nrt",
    "referenceOnly": true,
    "retrievalDate": "2026-06-09",
    "chunks": [
      "Nicotine replacement therapy (NRT) helps people who want to quit smoking by managing the withdrawal symptoms and cravings that make quitting hard. Using NRT increases the chances of successfully quitting by roughly 50 to 70 percent compared with quitting without it.",
      "Nicotine withdrawal commonly causes restlessness, increased appetite, low mood or depression, irritability, and intense cravings. These cravings typically peak about two to three days after a person stops smoking, then gradually ease over the following weeks.",
      "NRT works by delivering nicotine that binds to nicotinic-cholinergic receptors in the brain, which triggers dopamine release in reward-related areas such as the frontal cortex, mesolimbic region, and corpus striatum. This produces the pleasurable and stimulating sensations that smokers normally get from cigarettes, but without the smoke. By substituting a controlled source of nicotine, NRT blunts withdrawal while the person works on breaking the smoking habit.",
      "NRT comes in several forms suited to different needs and preferences. Long-acting transdermal patches provide a steady background level of nicotine throughout the day, while short-acting forms such as gum, lozenges, inhalers, and nasal spray act quickly to relieve sudden cravings. Many people combine a patch with a short-acting form for better craving control.",
      "Short-acting NRT forms work best when used correctly. Nicotine gum should be chewed slowly and then parked against the cheek rather than chewed continuously, and lozenges should be allowed to dissolve slowly over 20 to 30 minutes instead of being swallowed or bitten. Acidic drinks like coffee or soda can reduce absorption, so it helps to avoid them shortly before and during use.",
      "Common side effects of NRT depend on the form used. Patches can cause skin irritation at the application site and vivid dreams, while gum and lozenges may cause mouth or throat irritation, hiccups, or oral ulcers. Other possible effects include nausea, headache, and palpitations, and NRT should be used cautiously by people with cardiovascular disease, with discontinuation if palpitations develop.",
      "Certain groups need extra caution with NRT. For pregnant individuals, comprehensive behavioral support is the preferred first approach, and NRT is considered only when counseling alone is not enough, since nicotine carries theoretical risks to the fetus even though NRT avoids the carbon monoxide and other toxins in cigarette smoke. NRT safety has not been established for people under 18, and older adults or those with liver, kidney, or heart impairment may need lower doses.",
      "Combining medications can improve quit success for some people. Bupropion, an antidepressant, paired with a nicotine patch can enhance results, and varenicline may be combined with NRT under clinical guidance, though this raises the chance of nausea and skin reactions. Extended treatment lasting longer than 12 weeks is sometimes recommended over standard shorter courses when NRT is combined with other cessation medications.",
      "Successful cessation works best as a team effort with ongoing support rather than medication alone. Regular follow-up visits help check on side effects, confirm the person is using NRT correctly, and provide behavioral encouragement. Interprofessional care involving clinicians, nurses, pharmacists, and mental health support, such as structured programs like the Ottawa Model for Smoking Cessation, is associated with higher quit rates.",
      "Nicotine overdose is possible if too much NRT is used, especially alongside continued smoking. Warning signs include nausea, vomiting, diarrhea, dizziness, rapid heartbeat, weakness, and difficulty breathing, and these warrant prompt medical attention. Following the recommended dosing and not smoking while using NRT helps avoid toxicity."
    ]
  },
  {
    "sourceUrl": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7874528/",
    "sourceName": "PubMed Central",
    "domain": "ncbi.nlm.nih.gov",
    "topic": "behavioral",
    "referenceOnly": false,
    "retrievalDate": "2026-06-09",
    "chunks": [
      "Cigarette smoking remains the leading preventable cause of morbidity and mortality in the United States and accounts for about 30% of cancer deaths. As of 2017, smoking prevalence was 14% among U.S. adults, but it was substantially higher among vulnerable groups. Rates reached 41% among individuals with serious mental illness, 25% among those with disabilities, 26% among people earning under $35,000 a year, and 31% among the uninsured.",
      "Cognitive behavioral therapy (CBT) for smoking cessation focuses on identifying and changing maladaptive thought and behavior patterns. It typically includes problem-solving, coping skills rooted in relapse-prevention theory, and cognitive restructuring. Participants usually meet with a provider for sessions ranging from 50 minutes to 2 hours across multiple visits.",
      "In people with schizophrenia or bipolar disorder, a double-blind randomized trial found that combining medication with CBT was far more effective than behavioral therapy alone. At 52-week follow-up, the combined approach achieved 60% tobacco abstinence versus 19% for placebo plus CBT. The authors concluded that CBT without medication is not as effective as combined medication plus CBT for this population.",
      "Among people receiving substance use treatment, adding nicotine replacement therapy to CBT improved smoking cessation outcomes at 6 months. For people living with HIV, a 9-week integrated program of one psychoeducational session plus eight CBT sessions targeting smoking, anxiety, and depression produced 59% abstinence at end of treatment and 46% at 6 months, compared with 9% and 5% in the control group.",
      "In a group-based CBT program paired with a nicotine patch among racial and ethnic minorities, African American and Hispanic participants reported greater decreases in stress than Caucasian participants. Reductions in stress and depression were associated with increased abstinence. This suggests that addressing emotional distress can be an important lever for cessation in minority populations.",
      "Combining contingency management (financial incentives for staying abstinent) with group-based CBT outperformed CBT alone at every measured point. Abstinence reached 95.3% versus 59.2% right after treatment, 72.1% versus 34.7% at one month, and 51.2% versus 28.6% at six months. Adding tangible rewards for abstinence substantially strengthened behavioral treatment outcomes.",
      "For pregnant smokers, adding an emotion regulation component to CBT improved results over a health and lifestyle comparison combined with CBT. The emotion-regulation group achieved higher abstinence rates and smoked fewer cigarettes per day at 2- and 4-month follow-ups. This points to emotional self-regulation skills as a useful enhancement to standard behavioral treatment during pregnancy.",
      "Smartphone and app-based delivery of CBT shows promise for cessation. In one trial, a hybrid app combining acceptance and commitment therapy with CBT produced 13% abstinence versus 8% for a standard quit-guide app, with the most-used features being CBT-based quit planning and smoking tracking. People less likely to engage with these apps included women, those with lower education, heavier smokers, and those with depression, highlighting a need for better engagement strategies.",
      "Mindfulness-based interventions (MBIs) aim to increase awareness of one's environment, thoughts, emotions, and physical sensations as they relate to craving, and to build the capacity to sit with discomfort rather than act on it. Participants typically practice mindfulness meditation six days a week in group sessions over roughly eight weeks, meeting about two hours weekly. The goal is to change the relationship between craving and smoking rather than simply suppressing urges.",
      "Evidence on mindfulness-based interventions for cessation is mixed but encouraging for relapse recovery. In the largest trial comparing MBI, CBT, and usual care among low-income smokers, there were no significant overall differences in abstinence, but participants in the MBI group who were still smoking at the last session were most likely to regain abstinence afterward. A modified MBI for people with mild intellectual disability produced higher abstinence rates through one-year follow-up and fewer cigarettes per day among those who kept smoking.",
      "Technology-delivered mindfulness training has been tested through web programs, text messaging, and smartphone apps. A web-based mindfulness program with coaching calls achieved 23.1% abstinence at four months and 15.4% at six months. In app-based studies, mindfulness did not always raise quit rates over comparison conditions, but it weakened the link between craving and cigarettes smoked over time, which could support long-term cessation. Adding ongoing text support appeared especially beneficial for participants living below the poverty line.",
      "Key gaps remain in cessation research and practice. There is a need for scalable interventions tailored to vulnerable populations, head-to-head studies to determine whether CBT or mindfulness works better for specific individuals, and effective approaches for cancer survivors, where current evidence shows a lack of proven interventions. Improving engagement among underrepresented groups in technology-delivered programs is also a priority."
    ]
  },
  {
    "sourceUrl": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7163392/",
    "sourceName": "PubMed Central",
    "domain": "ncbi.nlm.nih.gov",
    "topic": "mechanism",
    "referenceOnly": false,
    "retrievalDate": "2026-06-09",
    "chunks": [
      "Nicotine addiction is driven by how nicotine interacts with receptors and neurotransmitter systems in the brain to create dependence, craving, and withdrawal. Understanding this neurobiology explains why quitting smoking is physically difficult and not simply a matter of willpower.",
      "Most of the nicotine a person takes in (roughly 70 to 80 percent) is broken down into cotinine in the liver by microsomal enzymes. The enzyme cytochrome P450 2A6 (CYP2A6) is responsible for about 90 percent of this breakdown and is the main pathway that deactivates nicotine in humans.",
      "Inherited differences in the CYP2A6 gene appear to influence smoking behavior. People who metabolize nicotine more slowly because of variations in this gene may be partly protected from becoming nicotine-dependent smokers, since slower metabolism changes how nicotine accumulates and is cleared.",
      "Nicotine raises the level of dopamine outside cells in the nucleus accumbens, a key reward region of the brain. It does this by activating the mesolimbic dopamine system through nicotinic receptors located in the ventral tegmental area (VTA) and the nucleus accumbens, which is central to the rewarding, reinforcing feeling of smoking.",
      "Nicotinic acetylcholine receptors come in different subunit combinations, and nicotine is most sensitive at the alpha-4 beta-2 receptor arrangement. Experiments in mice bred to lack the beta-2 subunit (knockout mice) showed reduced addictive responses, identifying that subunit as important to nicotine's addictive properties.",
      "Repeated tobacco use delivers pulses of nicotine to the central nervous system while keeping a steady background level of nicotine in the blood throughout the day of smoking. This continuous exposure leads the nicotinic receptors to become desensitized, which shapes the cycle of tolerance and craving that smokers experience.",
      "The first cigarette of the day tends to feel the most rewarding because the overnight break from smoking lets desensitized nicotinic receptors recover and become active again. As the number of active receptor sites increases overnight and into the early morning, withdrawal symptoms and craving intensify, which is why the morning urge to smoke is often strongest.",
      "Brain imaging with PET scans shows that tobacco use produces a marked reduction in the activity of monoamine oxidase (MAO), the enzyme that normally breaks down dopamine. Lowering both forms of this enzyme, MAO-A and MAO-B, results in higher dopamine levels, adding to nicotine's reinforcing effect beyond its direct action on nicotinic receptors.",
      "Nicotine also acts on other neurotransmitter systems involved in mood and reward. Nicotinic agonists trigger a calcium-dependent release of GABA in parts of the brain, and ongoing daily nicotine exposure lowers serotonin (5-HT) activity in the hippocampus, changes that contribute to the mood disturbances felt during withdrawal.",
      "Nicotine is a toxic substance, and the estimated toxic dose is around 40 to 60 mg in adults, roughly 0.8 to 1 mg per kilogram of body weight, with a much lower threshold of about 10 mg in children. This underscores that nicotine-containing products should be kept away from children and used cautiously."
    ]
  },
  {
    "sourceUrl": "https://pmc.ncbi.nlm.nih.gov/articles/PMC10984029/",
    "sourceName": "PubMed Central",
    "domain": "ncbi.nlm.nih.gov",
    "topic": "teen",
    "referenceOnly": false,
    "retrievalDate": "2026-06-09",
    "chunks": [
      "This qualitative study explored why adolescents want to quit vaping, what barriers they face, and which cessation strategies they recommend. Researchers conducted semi-structured interviews with 11 high school students who had vaped nicotine in the past 90 days. The goal was to ground vaping-cessation support in the lived experience of teens who vape.",
      "Teens cited several reasons for wanting to quit vaping. These included the financial cost of devices and pods, health worries such as lung damage, reduced lung capacity, asthma, and cough, and the toll on mood and focus including irritability, depressive mood swings, worsening anxiety, and distraction from schoolwork. Many also described being addicted, experiencing strong cravings and feeling desperate when they could not vape.",
      "Adolescents described 'nic-sick' symptoms tied to nicotine, including nausea, headaches, and vomiting from withdrawal or from taking in too much nicotine. These physical effects were a recurring motivator to cut back or quit. The discomfort made vaping feel less appealing over time.",
      "When unable to vape, participants reported withdrawal and craving symptoms such as feeling desperate, anxious, depressed, impatient, restless, irritable, unable to concentrate, and getting headaches. These symptoms appeared between vaping sessions and reinforced continued use. They illustrate how nicotine dependence drives the cycle of cravings in young people.",
      "Quitting was hard and usually took repeated attempts. Nearly all participants (9 of 11) had tried to quit multiple times, ranging from two to four or more attempts, and most described the experience as very difficult with notable irritability and stress. Only one participant successfully quit after a single attempt.",
      "Several barriers made quitting harder for adolescents. Key obstacles included being around peers who vape and facing social pressure, easy access to vape products through friends, and stress from school or family problems. The ongoing appeal of new flavors and products also pulled teens back toward vaping.",
      "Teens recommended behavioral strategies for quitting, centered on changing environment and social context. These included avoiding people who are vaping and places where vaping happens, seeking social support from friends and family, and firmly declining offers to resist peer pressure. Learning from peer role models who had successfully quit was also seen as motivating.",
      "Distraction was a favored coping tool for managing cravings. Adolescents suggested redirecting urges through activities like gaming, chewing gum, eating mints, or other hobbies. The idea was to occupy the hands and attention until a craving passed.",
      "Participants mentioned nicotine patches and nicotine gum as possible aids, but some incorrectly assumed these products could help youth quit vaping. Researchers note that nicotine replacement therapy is not FDA-approved for those under 18 years of age. This points to a gap between what teens believe about NRT and its approved use in minors.",
      "Teens endorsed technology-based support for cessation, with text messaging being the most widely favored channel. Other suggested options included social media, email, and video games used as distraction. One creative suggestion was a placebo vaping device containing only water to mimic the habit without nicotine.",
      "Many adolescents had started vaping to manage anxiety, since nicotine is known to produce a short-term anxiolytic effect. However, participants reported that vaping ultimately made their anxiety worse rather than better, because of the withdrawal symptoms they experienced between sessions. This highlights how using nicotine to cope with stress can deepen both dependence and anxiety."
    ]
  }
];
