#!/usr/bin/env node
/**
 * build-corpus.mjs — turn the Scout→Fetch→Curate workflow output into the typed
 * knowledge/corpus.ts the RAG ingest pipeline reads.
 *
 * Usage:  node scripts/build-corpus.mjs <workflow-result.json>
 *
 * Re-enforces the allowlist + topic enum as a final gate (hard rule: no valid
 * source = not ingested). See knowledge/README.md.
 */
import { readFileSync, writeFileSync } from 'node:fs';

const ALLOWLIST = [
  'cdc.gov', 'smokefree.gov', 'nida.nih.gov', 'cancer.gov',
  'who.int', 'mayoclinic.org', 'cochranelibrary.com', 'ncbi.nlm.nih.gov',
];
const TOPICS = ['mechanism', 'withdrawal', 'cravings', 'behavioral', 'relapse', 'nrt', 'teen'];

const onAllowlist = (url) => {
  try {
    const h = new URL(url).hostname.toLowerCase();
    return ALLOWLIST.some((d) => h === d || h.endsWith(`.${d}`));
  } catch {
    return false;
  }
};

const inPath = process.argv[2];
if (!inPath) {
  console.error('usage: node scripts/build-corpus.mjs <workflow-result.json>');
  process.exit(1);
}

let raw = readFileSync(inPath, 'utf8');
// The result may be wrapped; isolate the JSON object.
const start = raw.indexOf('{');
const end = raw.lastIndexOf('}');
const parsed = JSON.parse(raw.slice(start, end + 1));
// Workflow output is wrapped: { summary, logs, result: { entries } }.
const data = parsed.result ?? parsed;
const entriesIn = Array.isArray(data.entries) ? data.entries : [];

const seen = new Set();
const entries = [];
let rejected = 0;
for (const e of entriesIn) {
  const chunks = (e.chunks || []).map((c) => String(c).trim()).filter(Boolean);
  if (!e.sourceUrl || !onAllowlist(e.sourceUrl) || !TOPICS.includes(e.topic) || !chunks.length) {
    rejected++;
    continue;
  }
  if (seen.has(e.sourceUrl)) continue;
  seen.add(e.sourceUrl);
  entries.push({
    sourceUrl: e.sourceUrl,
    sourceName: e.sourceName || new URL(e.sourceUrl).hostname,
    domain: e.domain || new URL(e.sourceUrl).hostname.replace(/^www\./, ''),
    topic: e.topic,
    referenceOnly: !!e.referenceOnly,
    retrievalDate: e.retrievalDate || new Date().toISOString().slice(0, 10),
    chunks,
  });
}

const byTopic = {};
for (const e of entries) byTopic[e.topic] = (byTopic[e.topic] || 0) + 1;
const totalChunks = entries.reduce((n, e) => n + e.chunks.length, 0);

const header = `/**
 * Curated cessation corpus — the ONLY content the RAG index ingests.
 *
 * GENERATED by scripts/build-corpus.mjs from the Scout→Fetch→Curate subagent
 * team. Do NOT hand-edit chunk text; re-run the pipeline (knowledge/README.md).
 * Every entry carries its source URL + retrieval date (hard rule: no source =
 * not ingested). Built: ${data.retrievalDate || 'n/a'} · ${entries.length} sources · ${totalChunks} chunks.
 */
import type { Topic } from './sources.config';

export type CorpusEntry = {
  sourceUrl: string;
  sourceName: string;
  domain: string;
  topic: Topic;
  /** true = contains dosing/clinical specifics: stored for reference, never repeated verbatim by Sage. */
  referenceOnly: boolean;
  retrievalDate: string;
  chunks: string[];
};

export const CORPUS: CorpusEntry[] = ${JSON.stringify(entries, null, 2)};
`;

writeFileSync(new URL('../knowledge/corpus.ts', import.meta.url), header);
console.log(`Wrote knowledge/corpus.ts: ${entries.length} sources, ${totalChunks} chunks, rejected ${rejected}.`);
console.log('By topic:', byTopic);
